import pickle
from itertools import product
from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure()
ax = plt.axes()

# get input from pickle file generated by SimpleVRP.py
file = open('inp_out.pickle','rb')
data = pickle.load(file)

(vars, depots, customers, trucks, nodes, costs) = data
print(vars)
for var in vars:
    x = vars[var]
    if x != 0:
        print(var, '=', round(x,1))
# create lists for the depo with id and coordinates
depo_id = [depo.id for depo in depots]
depo_x = [round(depo.x,1) for depo in depots]
depo_y = [round(depo.y,1) for depo in depots]


#plot the depo points
ax.scatter(depo_x, depo_y, c='b', marker = '^')

# plot and label depots
for id, x, y in zip(depo_id, depo_x, depo_y):
    print(id, x, y)
    label = f"d{id}" #\n ({x},{y})"
    ax.text(x+2, y, label)

customer_id = [customer.id for customer in customers]
customer_x = [round(customer.x,1) for customer in customers]
customer_y = [round(customer.y,1) for customer in customers]


#plot the customer points
ax.scatter(customer_x, customer_y, c='r', marker = 'o')

# plot and label customers
for id, x, y in zip(customer_id, customer_x, customer_y):
    print(id, x, y)
    label = f"c{id}" # \n ({x},{y})"
    ax.text(x+2, y, label)

ax.set_xlabel('x-axis')
ax.set_ylabel('y-axis')
ax.axes.set_xlim(left=0, right=100)
ax.axes.set_ylim(bottom=0, top=100)
#plt.show()